name: probar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: analizar
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=proyectofinal
            #-Dsonar.sources= # opcional, directorio base del proyecto por defecto
            #-Dsonar.tests= # opcional. Para más info sobre Cobertura de Código, consulta https://docs.sonarcloud.io/enriching/test-coverage/overview/
            #-Dsonar.verbose= # opcional, por defecto es falso
